### PR TITLE
Feature/structure

### PR DESCRIPTION
**Pull request by glassdimly**

### CODE REVIEW

**Comment by brodavi** [comment]
+1 80 chars wrap (yay teletypes)

Also, not sure if I mentioned this, but: https://github.com/feross/standard

**Comment by eethann** [comment]
I think we should start pretty simple. Just folders for each of the major platforms, with README's inside that we can then shard as needed if they get more complicated.

**Comment by glassdimly** [comment]
Added 80-char linebreaks, removed developer wisdom. There were some weird files in the structure that I removed. In general I think that having sub-folders for tutorials/gotchas or other information is reasonable. I've added an explanation of this to the readme. I.e., "flexbox" folder in css which might contain either information about flexbox (tutorials) or could contain bugs in the flexbox spec as we discover them. I can nix these if folks feel otherwise.

**Comment by brodavi** [comment]
added some stuff about git... ripped off some of ThoughtBot's guide, edited for non-github-specific use, and some other minor things

**Comment by glassdimly** [comment]
Should we eliminate the standards vs. best practices distinction, folks?

**Comment by brodavi** [comment]
Hmm I think that might be a good idea. If we really need to specify _must do_ vs _good idea_, we can probably say so on a case by case basis.

**Pull request merged**
